#include "media/AudioSourceReader.h"

#include "media/AudioBuffer.h"
#include "media/WaveformData.h"

#include <QDir>
#include <QFileInfo>
#include <QTest>

#include <algorithm>
#include <cmath>

using atk::media::AudioChunk;
using atk::media::AudioFormat;
using atk::media::AudioSourceReader;
using atk::media::WaveformData;
using atk::media::WaveformPeak;

namespace {

/// Generated by cmake/ATKTestMedia.cmake. Ten seconds at 24 fps with audio
/// whose loudness is known at every moment:
///
///   0.5-1.0  quiet tone     1.5-2.0  loud tone
///   3.0-3.5  quiet tone     8.0-8.5  loud tone
///   everything else silent
/// Thresholds separating the fixture's three states, set from what it actually
/// produces rather than from what the filter graph nominally asks for:
///
///   silence     measures below 0.02
///   quiet tone  measures about 0.037
///   loud tone   measures above 0.05
///
/// A tone threshold of 0.025 therefore separates "there is sound here" from
/// "there is not" with roughly a 2x margin on each side.
constexpr float kToneFloor = 0.025f;
constexpr float kSilenceCeiling = 0.02f;

constexpr int64_t kQuietToneStartUs = 500'000;
constexpr int64_t kLoudToneStartUs = 1'500'000;
constexpr int64_t kLateToneStartUs = 8'000'000;

QString reviewFixture()
{
    return QDir(QString::fromUtf8(ATK_TEST_MEDIA_DIR))
        .filePath(QStringLiteral("atk_review_10s.mkv"));
}

AudioFormat deviceFormat()
{
    AudioFormat format;
    format.sampleRate = 48000;
    format.channelCount = 1;
    format.bytesPerSample = 2;
    return format;
}

/// Largest absolute sample in a buffer of interleaved signed 16-bit PCM.
float peakAmplitude(const QByteArray& pcm)
{
    const auto* samples = reinterpret_cast<const int16_t*>(pcm.constData());
    const qsizetype count = pcm.size() / 2;

    int32_t peak = 0;
    for (qsizetype i = 0; i < count; ++i) {
        peak = std::max<int32_t>(peak, std::abs(static_cast<int32_t>(samples[i])));
    }
    return static_cast<float>(peak) / 32768.0f;
}

} // namespace

/// Covers the audio path that scrubbing and the waveform both depend on:
/// reading PCM at an exact media position, and turning it into peaks.
class TestAudioReview : public QObject {
    Q_OBJECT

private slots:
    void initTestCase();

    // --- Reader -----------------------------------------------------------
    void opensAudioOfAVideoFile();
    void reportsDurationAndStartTime();
    void rejectsFileWithoutAudio();

    // --- Scrub grain accuracy --------------------------------------------
    void grainStartsAtRequestedPosition_data();
    void grainStartsAtRequestedPosition();
    void grainHasRequestedDuration();
    void grainContentMatchesKnownSegments_data();
    void grainContentMatchesKnownSegments();
    void repeatedReadsAreStable();
    void seekingBackwardsWorks();

    // --- Waveform ---------------------------------------------------------
    void waveformReflectsKnownSegments();
    void waveformSilenceIsQuiet();
};

void TestAudioReview::initTestCase()
{
    if (!QFileInfo::exists(reviewFixture())) {
        QSKIP("Review fixture not found; build the atk_test_media target first.");
    }
}

// ---------------------------------------------------------------------------
// Reader
// ---------------------------------------------------------------------------

void TestAudioReview::opensAudioOfAVideoFile()
{
    AudioSourceReader reader;
    QString error;

    // The reader takes its own handle on a file that also has video, without
    // needing the video decoder to be involved at all.
    QVERIFY2(reader.open(reviewFixture(), deviceFormat(), &error), qPrintable(error));
    QVERIFY(reader.isOpen());
    QCOMPARE(reader.format().sampleRate, 48000);
    QCOMPARE(reader.format().channelCount, 1);
}

void TestAudioReview::reportsDurationAndStartTime()
{
    AudioSourceReader reader;
    QVERIFY(reader.open(reviewFixture(), deviceFormat(), nullptr));

    QVERIFY(reader.durationUs() > 9'000'000);
    QVERIFY(reader.durationUs() < 11'000'000);

    // The start offset must be reported, not assumed zero -- ignoring it would
    // slide every grain and every waveform bucket against the picture.
    QVERIFY(reader.startTimeUs() >= 0);
}

void TestAudioReview::rejectsFileWithoutAudio()
{
    // A missing file stands in for "nothing to read": the reader must fail
    // cleanly so scrubbing continues visually rather than erroring.
    AudioSourceReader reader;
    QString error;
    QVERIFY(!reader.open(QStringLiteral("C:/definitely/not/here_a1b2.mkv"),
                         deviceFormat(), &error));
    QVERIFY(!reader.isOpen());
    QVERIFY(!error.isEmpty());
}

// ---------------------------------------------------------------------------
// Scrub grain accuracy
// ---------------------------------------------------------------------------

void TestAudioReview::grainStartsAtRequestedPosition_data()
{
    QTest::addColumn<qint64>("requestUs");

    QTest::newRow("0.5s") << qint64(500'000);
    QTest::newRow("1s")   << qint64(1'000'000);
    QTest::newRow("2s")   << qint64(2'000'000);
    QTest::newRow("3.5s") << qint64(3'500'000);
    QTest::newRow("8s")   << qint64(8'000'000);
}

void TestAudioReview::grainStartsAtRequestedPosition()
{
    QFETCH(qint64, requestUs);

    AudioSourceReader reader;
    QVERIFY(reader.open(reviewFixture(), deviceFormat(), nullptr));

    QByteArray pcm;
    int64_t actualStartUs = -1;
    QString error;
    QVERIFY2(reader.readRange(requestUs, 80'000, pcm, &actualStartUs, &error),
             qPrintable(error));

    // Sub-frame accuracy. Seeking lands on a packet boundary at or before the
    // request, and readRange() trims the lead-in; without that trimming a grain
    // could begin tens of milliseconds early, which for lip-sync review is
    // simply the wrong sound.
    const int64_t deltaUs = std::abs(actualStartUs - requestUs);
    constexpr int64_t kOneFrameAt24FpsUs = 41'667;
    QVERIFY2(deltaUs < kOneFrameAt24FpsUs / 2,
             qPrintable(QStringLiteral("grain started %1 us from the request").arg(deltaUs)));
}

void TestAudioReview::grainHasRequestedDuration()
{
    AudioSourceReader reader;
    QVERIFY(reader.open(reviewFixture(), deviceFormat(), nullptr));

    QByteArray pcm;
    int64_t actualStartUs = 0;
    QVERIFY(reader.readRange(2'000'000, 80'000, pcm, &actualStartUs, nullptr));

    const AudioFormat format = reader.format();
    const int64_t durationUs = format.bytesToMicroseconds(pcm.size());

    // Trimmed to the request rather than returning whole packets.
    QVERIFY2(std::abs(durationUs - 80'000) < 5'000,
             qPrintable(QStringLiteral("grain was %1 us long").arg(durationUs)));

    // A whole number of sample frames, or the channel interleaving would slip.
    QCOMPARE(pcm.size() % format.bytesPerFrame(), qsizetype(0));
}

void TestAudioReview::grainContentMatchesKnownSegments_data()
{
    QTest::addColumn<qint64>("positionUs");
    QTest::addColumn<bool>("expectTone");

    QTest::newRow("silence at 0.1s")   << qint64(100'000)          << false;
    QTest::newRow("quiet tone at 0.7s")<< qint64(700'000)          << true;
    QTest::newRow("silence at 1.2s")   << qint64(1'200'000)        << false;
    QTest::newRow("loud tone at 1.7s") << kLoudToneStartUs + 200'000 << true;
    QTest::newRow("silence at 2.5s")   << qint64(2'500'000)        << false;
    QTest::newRow("quiet tone at 3.2s")<< qint64(3'200'000)        << true;
    QTest::newRow("silence at 5s")     << qint64(5'000'000)        << false;
    QTest::newRow("loud tone at 8.2s") << kLateToneStartUs + 200'000 << true;
}

void TestAudioReview::grainContentMatchesKnownSegments()
{
    QFETCH(qint64, positionUs);
    QFETCH(bool, expectTone);

    AudioSourceReader reader;
    QVERIFY(reader.open(reviewFixture(), deviceFormat(), nullptr));

    QByteArray pcm;
    int64_t actualStartUs = 0;
    QVERIFY(reader.readRange(positionUs, 60'000, pcm, &actualStartUs, nullptr));

    // This is the real assertion behind "the audio you hear belongs to the
    // moment you are pointing at": the grain fetched for a position must
    // contain what the fixture puts there.
    const float peak = peakAmplitude(pcm);
    if (expectTone) {
        QVERIFY2(peak > kToneFloor,
                 qPrintable(QStringLiteral("expected tone at %1 us, peak was %2")
                                .arg(positionUs).arg(peak)));
    } else {
        QVERIFY2(peak < kSilenceCeiling,
                 qPrintable(QStringLiteral("expected silence at %1 us, peak was %2")
                                .arg(positionUs).arg(peak)));
    }
}

void TestAudioReview::repeatedReadsAreStable()
{
    AudioSourceReader reader;
    QVERIFY(reader.open(reviewFixture(), deviceFormat(), nullptr));

    // Scrubbing revisits the same position constantly; the answer must not
    // drift with repetition.
    QByteArray first;
    int64_t firstStart = 0;
    QVERIFY(reader.readRange(kLoudToneStartUs + 100'000, 60'000, first, &firstStart, nullptr));

    for (int i = 0; i < 5; ++i) {
        QByteArray again;
        int64_t againStart = 0;
        QVERIFY(reader.readRange(kLoudToneStartUs + 100'000, 60'000, again, &againStart, nullptr));
        QCOMPARE(againStart, firstStart);
        QCOMPARE(again, first);
    }
}

void TestAudioReview::seekingBackwardsWorks()
{
    AudioSourceReader reader;
    QVERIFY(reader.open(reviewFixture(), deviceFormat(), nullptr));

    QByteArray late;
    QVERIFY(reader.readRange(kLateToneStartUs + 200'000, 60'000, late, nullptr, nullptr));
    QVERIFY(peakAmplitude(late) > kToneFloor);

    // Dragging backwards is the common review gesture, so a backward seek must
    // land as accurately as a forward one.
    QByteArray early;
    int64_t earlyStart = 0;
    QVERIFY(reader.readRange(kQuietToneStartUs + 200'000, 60'000, early, &earlyStart, nullptr));
    QVERIFY(peakAmplitude(early) > kToneFloor);
    QVERIFY(std::abs(earlyStart - (kQuietToneStartUs + 200'000)) < 20'000);
}

// ---------------------------------------------------------------------------
// Waveform
// ---------------------------------------------------------------------------

void TestAudioReview::waveformReflectsKnownSegments()
{
    AudioSourceReader reader;
    AudioFormat analysisFormat;
    analysisFormat.sampleRate = 22050;
    analysisFormat.channelCount = 1;
    analysisFormat.bytesPerSample = 2;

    QVERIFY(reader.open(reviewFixture(), analysisFormat, nullptr));

    // Mirrors what WaveformWorker does, without needing a thread.
    const int64_t samplesPerBucket =
        (int64_t(analysisFormat.sampleRate) * WaveformData::kBaseBucketUs) / 1'000'000;

    WaveformData waveform;
    QVector<WaveformPeak> buckets;
    WaveformPeak current;
    int64_t samplesInBucket = 0;
    bool started = false;

    QString error;
    reader.scan(
        [&](const AudioChunk& chunk) {
            const auto* samples = reinterpret_cast<const int16_t*>(chunk.pcm.constData());
            const qsizetype count = chunk.pcm.size() / 2;
            for (qsizetype i = 0; i < count; ++i) {
                const float value = static_cast<float>(samples[i]) / 32768.0f;
                if (!started) {
                    current.minimum = value;
                    current.maximum = value;
                    started = true;
                } else {
                    current.minimum = std::min(current.minimum, value);
                    current.maximum = std::max(current.maximum, value);
                }
                if (++samplesInBucket >= samplesPerBucket) {
                    buckets.append(current);
                    samplesInBucket = 0;
                    started = false;
                }
            }
        },
        {}, &error);

    waveform.appendBaseBuckets(buckets);
    QVERIFY2(!waveform.isEmpty(), qPrintable(error));

    // The peaks must line up with where the fixture puts the tones -- this is
    // what makes the drawn waveform trustworthy as a timing reference.
    QVERIFY(waveform.peakOverRange(0, kQuietToneStartUs + 100'000,
                                   kQuietToneStartUs + 400'000).amplitude() > 0.01f);
    QVERIFY(waveform.peakOverRange(0, kLoudToneStartUs + 100'000,
                                   kLoudToneStartUs + 400'000).amplitude() > 0.05f);
    QVERIFY(waveform.peakOverRange(0, kLateToneStartUs + 100'000,
                                   kLateToneStartUs + 400'000).amplitude() > 0.05f);

    // And the loud segment must actually read louder than the quiet one.
    const float quiet = waveform.peakOverRange(0, kQuietToneStartUs + 100'000,
                                               kQuietToneStartUs + 400'000).amplitude();
    const float loud = waveform.peakOverRange(0, kLoudToneStartUs + 100'000,
                                              kLoudToneStartUs + 400'000).amplitude();
    QVERIFY2(loud > quiet,
             qPrintable(QStringLiteral("loud %1 was not above quiet %2").arg(loud).arg(quiet)));
}

void TestAudioReview::waveformSilenceIsQuiet()
{
    AudioSourceReader reader;
    AudioFormat analysisFormat;
    analysisFormat.sampleRate = 22050;
    analysisFormat.channelCount = 1;
    analysisFormat.bytesPerSample = 2;
    QVERIFY(reader.open(reviewFixture(), analysisFormat, nullptr));

    // Between the segments the fixture is silent, and the waveform must show
    // that -- a review tool where silence looks like sound is useless.
    QByteArray pcm;
    QVERIFY(reader.readRange(5'000'000, 200'000, pcm, nullptr, nullptr));
    QVERIFY2(peakAmplitude(pcm) < kSilenceCeiling,
             qPrintable(QStringLiteral("silence measured %1").arg(peakAmplitude(pcm))));
}

QTEST_GUILESS_MAIN(TestAudioReview)
#include "tst_audioreview.moc"
